services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=file:/app/prisma/data.db
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama2
    volumes:
      - ./uploads:/app/uploads
      - ./prisma:/app/prisma
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 